# Generated by Django 3.1.1 on 2020-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bus/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=15),
        ),
    ]
